# Generated by Django 5.0.4 on 2024-05-01 20:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name: ')),
                ('email', models.EmailField(max_length=254)),
                ('who_i', models.TextField(max_length=250, verbose_name='Who_i: ')),
                ('price', models.IntegerField(verbose_name='Price: ')),
                ('phone_number', models.CharField(max_length=20)),
                ('doctor_id_image', models.ImageField(upload_to='doctor_ids')),
                ('start_time', models.TimeField(choices=[(datetime.time(0, 0), '0:00 AM'), (datetime.time(1, 0), '1:00 AM'), (datetime.time(2, 0), '2:00 AM'), (datetime.time(3, 0), '3:00 AM'), (datetime.time(4, 0), '4:00 AM'), (datetime.time(5, 0), '5:00 AM'), (datetime.time(6, 0), '6:00 AM'), (datetime.time(7, 0), '7:00 AM'), (datetime.time(8, 0), '8:00 AM'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(1, 0), '1:00 PM'), (datetime.time(2, 0), '2:00 PM'), (datetime.time(3, 0), '3:00 PM'), (datetime.time(4, 0), '4:00 PM'), (datetime.time(5, 0), '5:00 PM'), (datetime.time(6, 0), '6:00 PM'), (datetime.time(7, 0), '7:00 PM'), (datetime.time(8, 0), '8:00 PM'), (datetime.time(9, 0), '9:00 PM'), (datetime.time(10, 0), '10:00 PM'), (datetime.time(11, 0), '11:00 PM')])),
                ('end_time', models.TimeField(choices=[(datetime.time(1, 0), '1:00 AM'), (datetime.time(2, 0), '2:00 AM'), (datetime.time(3, 0), '3:00 AM'), (datetime.time(4, 0), '4:00 AM'), (datetime.time(5, 0), '5:00 AM'), (datetime.time(6, 0), '6:00 AM'), (datetime.time(7, 0), '7:00 AM'), (datetime.time(8, 0), '8:00 AM'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(1, 0), '1:00 PM'), (datetime.time(2, 0), '2:00 PM'), (datetime.time(3, 0), '3:00 PM'), (datetime.time(4, 0), '4:00 PM'), (datetime.time(5, 0), '5:00 PM'), (datetime.time(6, 0), '6:00 PM'), (datetime.time(7, 0), '7:00 PM'), (datetime.time(8, 0), '8:00 PM'), (datetime.time(9, 0), '9:00 PM'), (datetime.time(10, 0), '10:00 PM'), (datetime.time(11, 0), '11:00 PM'), (datetime.time(0, 0), '12:00 AM')])),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist'), ('Urologist', 'Urologist')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
