# Generated by Django 5.0.4 on 2024-05-06 11:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_patient_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(default='default_image.jpg', upload_to='doctor_images'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 6, 11, 52, 4, 364503, tzinfo=datetime.timezone.utc))),
                ('end_datetime', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 6, 11, 52, 4, 364503, tzinfo=datetime.timezone.utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
