# Generated by Django 5.0.4 on 2024-05-12 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_options_doctor_doctor_image_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='position',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Location',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria')], default='cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Location',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria')], default='cairo', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 12, 7, 14, 28, 903534, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 12, 7, 14, 28, 903534, tzinfo=datetime.timezone.utc)),
        ),
    ]
