# Generated by Django 5.0.4 on 2024-05-14 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patient_position_doctor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 14, 18, 34, 8, 276677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 14, 18, 34, 8, 276677, tzinfo=datetime.timezone.utc)),
        ),
    ]
